import os
from datetime import datetime
import boto3

s3_client = boto3.client("s3")

def handler(event, context):
    try:
        timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        filename = f"lambda_report_{timestamp}.txt"
        bucket_name = "local-test-bucket"
        
        tmp_file_path = f"/tmp/{filename}"
        
        with open(tmp_file_path, "w") as file:
            file.write("Automated Report\n")
            file.write(f"Generated by AWS Lambda at {datetime.now()}\n")
            file.write("File was generated inside a Lambda container")
            
        print(f"Uploading {filename} to S3 {bucket_name}")
        s3_client.upload_file(tmp_file_path, bucket_name, filename)
        
        print("Upload successfully")
        return {
            "statusCode": 200,
            "body": f"Successfully generated and uploaded {filename} to S3 {bucket_name}"
        }
    
    except Exception as e:
        print(f"Failed: {str(e)}")
        return {
            "statusCode": 500,
            "body": f"Error: {str(e)}"
        }